from datetime import datetime

def format_markdown_report(content: str, metadata: dict = None) -> str:
    """Format content into a structured Markdown report"""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    metadata = metadata or {}
    metadata_str = "\n".join([f"- {k}: {v}" for k, v in metadata.items()])
    
    return f"""# Research Report
Generated: {timestamp}

## Contents
{content}

## Metadata
- Generated by: Multi-Agent Collaborative System
- Date: {timestamp}
{metadata_str}
"""

def format_research_command(topic: str) -> str:
    """Format the research command for better results"""
    return f"""Search for '{topic}' and provide a comprehensive summary including:
    - Key findings and facts
    - Recent developments
    - Important impacts
    Please organize the information clearly."""